export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_LOADING = "SIGNUP_LOADING";

export const COMPANY_SUCCESS = "COMPANY_SUCCESS";
export const COMPANY_ERROR = "COMPANY_ERROR";
export const COMPANY_LOADING = "COMPANY_LOADING";

export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";

export const CREATE_STAFF = "GET_STAFF";
export const GET_ALL_STAFFS = "GET_ALL_STAFFS";
export const DELETE_STAFF = "DELETE_STAFF";
export const STAFF_ERROR = "STAFF_ERROR";
export const STAFF_LOADING = "STAFF_LOADING";

export const GET_LOCATION = "GET_LOCATION";
export const GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const LOCATION_ERROR = "LOCATION_ERROR";
export const LOCATION_LOADING = "LOCATION_LOADING";

export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";

export const PRODUCT_CREATED = "PRODUCT_CREATED";
export const PRODUCT_CATEGORY_CREATED = "PRODUCT_CATEGORY_CREATED";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_CATEGORY = "GET_ALL_PRODUCT_CATEGORY";
export const GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const LOADING_PRODUCT_CATEGORY = "LOADING_PRODUCT_CATEGORY";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_CATEGORY_ERROR = "PRODUCT_CATEGORY_ERROR";
