export const GET_USER = "GET_USER";
export const USER_ERROR = "USER_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_LOADING = "SIGNUP_LOADING";

export const COMPANY_SUCCESS = "COMPANY_SUCCESS";
export const GET_COMPANY = "GET_COMPANY";
export const GET_COMPANY_BY_CODE = "GET_COMPANY_BY_CODE";
export const COMPANY_UPDATED_SUCCESSFULLY = "COMPANY_UPDATED_SUCCESSFULLY";
export const COMPANY_ERROR = "COMPANY_ERROR";
export const COMPANY_LOADING = "COMPANY_LOADING";

export const ALERT_SUCCESS = "ALERT_SUCCESS";
export const ALERT_ERROR = "ALERT_ERROR";
export const ALERT_CLEAR = "ALERT_CLEAR";

export const CREATE_STAFF = "GET_STAFF";
export const GET_ALL_STAFFS = "GET_ALL_STAFFS";
export const DELETE_STAFF = "DELETE_STAFF";
export const STAFF_ERROR = "STAFF_ERROR";
export const STAFF_LOADING = "STAFF_LOADING";

export const GET_LOCATION = "GET_LOCATION";
export const GET_ALL_LOCATIONS = "GET_ALL_LOCATIONS";
export const DELETE_LOCATION = "DELETE_LOCATION";
export const LOCATION_ERROR = "LOCATION_ERROR";
export const LOCATION_LOADING = "LOCATION_LOADING";

export const OPEN_POPUP = "OPEN_POPUP";
export const CLOSE_POPUP = "CLOSE_POPUP";

export const PRODUCT_CREATED = "PRODUCT_CREATED";
export const PRODUCT_CATEGORY_CREATED = "PRODUCT_CATEGORY_CREATED";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_CATEGORY = "GET_ALL_PRODUCT_CATEGORY";
export const GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const UPDATE_PRODUCT_CATEGORY = "UPDATE_PRODUCT_CATEGORY";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const LOADING_PRODUCT_CATEGORY = "LOADING_PRODUCT_CATEGORY";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_CATEGORY_ERROR = "PRODUCT_CATEGORY_ERROR";

export const GET_SERVICE_GROUP = "GET_SERVICE_GROUP";
export const GET_ALL_SERVICE_GROUPS = "GET_ALL_SERVICE_GROUPS";
export const DELETE_SERVICE_GROUP = "DELETE_SERVICE_GROUP";
export const SERVICE_GROUP_ERROR = "SERVICE_GROUP_ERROR";
export const SERVICE_GROUP_LOADING = "SERVICE_GROUP_LOADING";

export const GET_SERVICE = "GET_SERVICE";
export const SERVICE = "SERVICE";
export const GET_ALL_SERVICE = "GET_ALL_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";
export const SERVICE_ERROR = "SERVICE_ERROR";
export const SERVICE_LOADING = "SERVICE_LOADING";
export const STAFF_ADDED = "STAFF_ADDED";
export const STAFF_REMOVED = "STAFF_REMOVED";
export const STAFF_ADDING_ERROR = "STAFF_ADDING_ERROR";

export const CREATE_PRODUCT_VARIANT = "GET_PRODUCT_VARIANT";
export const GET_ALL_PRODUCT_VARIANTS = "GET_ALL_PRODUCT_VARIANTS";
export const DELETE_PRODUCT_VARIANT = "DELETE_PRODUCT_VARIANT";
export const PRODUCT_VARIANT_ERROR = "PRODUCT_VARIANT_ERROR";
export const PRODUCT_VARIANT_LOADING = "PRODUCT_VARIANT_LOADING";
export const RERENDER = "RERENDER";

export const CLIENT_CREATED = "CLIENT_CREATED";
export const PET_CREATED = "PET_CREATED";
export const GET_CLIENT = "GET_CLIENT";
export const CLIENT_LOGIN = "CLIENT_LOGIN";
export const CLIENT_SIGNUP = "CLIENT_SIGNUP";
export const GET_ALL_CLIENT = "GET_ALL_CLIENT";
export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const LOADING_CLIENT = "LOADING_CLIENT";
export const CLIENT_ERROR = "CLIENT_ERROR";
export const CLIENT_ACTIVATED = "CLIENT_ACTIVATED";
export const CLIENT_DEACTIVATED = "CLIENT_DEACTIVATED";
export const GET_PET = "GET_PET";
export const PET_REMOVED = "PET_REMOVED";
export const PET_ADDING_ERROR = "PET_ADDING_ERROR";
export const SEVICE_DATA = "SEVICE_DATA";
export const CALENDER_DATA = "CALENDER_DATA";

export const CREATE_ORDER = "GET_ORDER";
export const CREATE_ONLINE_ORDER = "GET_ONLINE_ORDER";
export const CONFIRM_ONLINE_BOOKING = "CONFIRM_ONLINE_BOOKING";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ONLINE_ORDERS = "GET_ONLINE_ORDERS";
export const GET_PENDING_ONLINE_ORDERS = "GET_PENDING_ONLINE_ORDERS";
export const DELETE_ORDER = "DELETE_ORDER";
export const ORDER_ERROR = "ORDER_ERROR";
export const ORDER_LOADING = "ORDER_LOADING";

export const CREATE_PET = "CREATE_PET";
export const GET_ALL_PETS = "GET_ALL_PETS";
export const DELETE_PET = "DELETE_PET";
export const PET_ERROR = "PET_ERROR";
export const PET_LOADING = "PET_LOADING";

export const CREATE_PET_CATEGORY = "CREATE_PET_CATEGORY";
export const UPDATE_PET_CATEGORY = "UPDATE_PET_CATEGORY";
export const GET_ALL_PETS_CATEGORY = "GET_ALL_PETS_CATEGORY";
export const DELETE_PET_CATEGORY = "DELETE_PET_CATEGORY";
export const PET_CATEGORY_ERROR = "PET_CATEGORY_ERROR";
export const PET_CATEGORY_LOADING = "PET_CATEGORY_LOADING";
export const RELOAD_PET = "RELOAD_PET";

export const CREATE_BANK_DETAILS = "CREATE_BANK_DETAILS";
export const GET_ALL_BANK_DETAILS = "GET_ALL_BANK_DETAILS";
export const DELETE_BANK_DETAILS = "DELETE_BANK_DETAILS";
export const BANK_DETAILS_ERROR = "BANK_DETAILS_ERROR";
export const BANK_DETAILS_LOADING = "BANK_DETAILS_LOADING";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_ALL_MESSAGES = "GET_ALL_MESSAGES";
export const DELETE_MESSAGE = "DELETE_MESSAGE";
export const MESSAGE_ERROR = "MESSAGE_ERROR";
export const MESSAGE_LOADING = "MESSAGE_LOADING";
